### PR TITLE
fix: readme.md small bug

### PR DESCRIPTION
**Pull request by regmicmahesh**

### CODE REVIEW

**Comment by regmicmahesh** [comment]
i will bring DMCA with me if u copy next time.

**Comment by regmicmahesh** [comment]
and sue you with million dollar

**Comment by CaffeineDuck** [comment]
@regmicmahesh  you also copied arko dai ko tho :bruh:

**Comment by CaffeineDuck** [comment]
dar lagyo don't booli @regmicmahesh

**Pull request merged**
